

services:

  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx/
      args:
        - CURRENT_UID=${CURRENT_UID}
        - CURRENT_GID=${CURRENT_GID}
    init: true
    user: ${CURRENT_UID}:${CURRENT_GID}
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
      - source: nginx_sites_available
        target: /etc/nginx/sites-available/default
    secrets:
      - source: server-certificate
        target: site.crt
      - source: server-key
        target: site.key
    depends_on:
      - wp-php
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  wp-php:
    container_name: wp-php
    build: ./requirements/wordpress/
    init: true
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
      - type: bind
        source: ./requirements/wordpress/conf/
        target: /etc/php/8.2/fpm/pool.d/
      - type: bind
        source: ./requirements/wordpress/tools/
        target: /tools/
    networks:
      - inception
    secrets:
      - source: mariadb_wpuser_password
        target: mariadb_wpuser_password
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - MARIADB_WPUSER_PASSWORD_FILE=${MARIADB_WPUSER_PASSWORD_FILE}
      - MARIADB_HOST=${MARIADB_HOST}
      - WP_CLI_CACHE_DIR=/var/www/html/

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb/
      args:
        - CURRENT_UID=${CURRENT_UID}
        - CURRENT_GID=${CURRENT_GID}
        - MARIADB_VERSION=${MARIADB_VERSION}
    init: true
    user: ${CURRENT_UID}:${CURRENT_GID}
    configs:
      - source: mariadb_config
        target: /etc/mysql/mariadb.conf.d/50-server.cnf
    secrets:
      - source: mariadb_root_password
        target: mariadb_root_password 
      - source: mariadb_wpuser_password
        target: mariadb_wpuser_password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    environment:
      - MARIADB_VERSION=${MARIADB_VERSION}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_ROOT_PASSWORD_FILE=${MARIADB_ROOT_PASSWORD_FILE}
      - MARIADB_WPUSER_PASSWORD_FILE=${MARIADB_WPUSER_PASSWORD_FILE}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}

networks:
  inception:   
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: "nfs"
      o: 'bind'
      device: /home/gwolf/data/wordpress
  mariadb:
    name: mariadb
    driver_opts:
      type: "nfs"
      o: 'bind'
      device: /home/gwolf/data/mariadb

configs:
  nginx_config:
    file: ./requirements/nginx/conf/nginx.conf
  nginx_sites_available:
    file: ./requirements/nginx/conf/default
  mariadb_config:
    file: ./requirements/mariadb/conf/50-server.cnf

secrets:
  server-certificate:
    file: ../secrets/site.crt
  server-key:
    file: ../secrets/site.key
  mariadb_root_password:
    file: ../secrets/mariadb_root_password.txt
  mariadb_wpuser_password:
    file: ../secrets/mariadb_wpuser_password.txt

