services:
  nginx:
    container_name: nginx
    build:
      context: ${DIR_REQUIREMENTS}/nginx/
      args:
        - USER_NAME=${USER_NAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - NGINX_VERSION=${NGINX_VERSION}
        - SSL_CERT_VERSION=${SSL_CERT_VERSION}
    init: true
    restart: always
    depends_on:
      wp-php:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
      - source: nginx_sites_available
        target: /etc/nginx/sites-available/default
    secrets:
      - source: server-certificate
        target: site.crt
      - source: server-key
        target: site.key
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  wp-php:
    container_name: wp-php
    build:
      context: ${DIR_REQUIREMENTS}/wordpress/
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - PHP_FPM_VERSION=${PHP_FPM_VERSION}
        - PHP_MYSQL_VERSION=${PHP_MYSQL_VERSION}
        - CURL_VERSION=${CURL_VERSION}
        - WP_CLI_VERSION=${WP_CLI_VERSION}
    init: true
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    configs:
      - source: fpm_config
        target: /etc/php/8.2/fpm/pool.d/www.conf
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    secrets:
      - source: mariadb_wpuser_password
        target: mariadb_wpuser_password
      - source: wordpress_admin_password
        target: wordpress_admin_password
      - source: wordpress_user_password
        target: wordpress_user_password
    environment:
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - WORDPRESS_ADMIN_MAIL=${WORDPRESS_ADMIN_MAIL}
      - WORDPRESS_ADMIN_PASSWORD_FILE=${WORDPRESS_ADMIN_PASSWORD_FILE}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_USER_MAIL=${WORDPRESS_USER_MAIL}
      - WORDPRESS_USER_PASSWORD_FILE=${WORDPRESS_USER_PASSWORD_FILE}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${USER_NAME}
      - MARIADB_WPUSER_PASSWORD_FILE=${MARIADB_WPUSER_PASSWORD_FILE}
      - MARIADB_HOST=${MARIADB_HOST}
      - WP_CLI_CACHE_DIR=${WP_CLI_CACHE_DIR}
      - DOMAIN_NAME=${DOMAIN_NAME}
    healthcheck:
      test: ["CMD", "wp", "core", "verify-checksums"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
  mariadb:
    container_name: mariadb
    build:
      context: ${DIR_REQUIREMENTS}/mariadb/
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - MARIADB_VERSION=${MARIADB_VERSION}
    init: true
    restart: always
    configs:
      - source: mariadb_config
        target: /etc/mysql/mariadb.conf.d/50-server.cnf
    secrets:
      - source: mariadb_root_password
        target: mariadb_root_password
      - source: mariadb_wpuser_password
        target: mariadb_wpuser_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    environment:
      - MARIADB_VERSION=${MARIADB_VERSION}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_ROOT_PASSWORD_FILE=${MARIADB_ROOT_PASSWORD_FILE}
      - MARIADB_WPUSER_PASSWORD_FILE=${MARIADB_WPUSER_PASSWORD_FILE}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${USER_NAME}
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
  adminer:
    container_name: adminer
    build:
      context: ${DIR_REQUIREMENTS}/bonus/adminer/
      args:
        - USERNAME=${USER_NAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - PHP_FPM_VERSION=${PHP_FPM_VERSION}
        - PHP_MYSQL_VERSION=${PHP_MYSQL_VERSION}
        - CURL_VERSION=${CURL_VERSION}
        - ADMINER_VERSION=${ADMINER_VERSION}
    init: true
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    configs:
      - source: adminer_config
        target: /etc/php/8.2/fpm/pool.d/www.conf
      - source: adminer-index.php
        target: /var/www/html/index.php
    networks:
      - inception
    environment:
      - ADMINER_DEFAULT_DRIVER=server
      - ADMINER_DEFAULT_DB=${WORDPRESS_DB_NAME}
      - ADMINER_DEFAULT_SERVER=${MARIADB_HOST}
      - ADMINER_DEFAULT_USERNAME=${USER_NAME}
  redis:
    container_name: redis
    build:
      context: ${DIR_REQUIREMENTS}/bonus/redis
      args:
        - USER_NAME=${USER_NAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - REDIS_VERSION=${REDIS_VERSION}
    init: true
    restart: always
    configs:
      - source: redis_config
        target: /etc/redis/redis.conf
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  ftp:
    container_name: ftp
    build:
      context: ${DIR_REQUIREMENTS}/bonus/ftp/
      args:
        - USER_NAME=${USER_NAME}
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - VSFTPD_VERSION=${VSFTPD_VERSION}
        - DB_UTIL_VERSION=${DB_UTIL_VERSION}
    init: true
    restart: always
    depends_on:
      wp-php:
        condition: service_healthy
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception
    configs:
      - source: ftp_config
        target: /etc/pam.d/vsftpd.virtual
    volumes:
      - wordpress_data:/home/${USER_NAME}/
    secrets:
      - source: ftp_user_password
        target: ftp_user_password
    environment:
      - USER_NAME=${USER_NAME}
      - FTP_USER_PASSWORD_FILE=${FTP_USER_PASSWORD_FILE}
  cadvisor:
    container_name: cadvisor
    build:
      context: ${DIR_REQUIREMENTS}/bonus/cadvisor/
      args:
        - CADVISOR_VERSION=${CADVISOR_VERSION}
        - CURL_VERSION=${CURL_VERSION}
    init: true
    restart: always
    ports:
      - 8080:8080
    networks:
      - inception
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - "/dev/kmsg:/dev/kmsg"
  website:
    container_name: website
    build:
      context: ${DIR_REQUIREMENTS}/nginx/
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - NGINX_VERSION=${NGINX_VERSION}
        - SSL_CERT_VERSION=${SSL_CERT_VERSION}
    init: true
    restart: always
    depends_on:
      - nginx
    configs:
      - source: website_config
        target: /etc/nginx/nginx.conf
      - source: website_sites_available
        target: /etc/nginx/sites-available/default
    volumes:
      - ${DIR_REQUIREMENTS}/bonus/website/:/var/www/html
    networks:
      - inception

networks:
  inception:
    name: inception

configs:
  nginx_config:
    file: ${DIR_REQUIREMENTS}/nginx/conf/nginx.conf
  nginx_sites_available:
    file: ${DIR_REQUIREMENTS}/nginx/conf/default
  mariadb_config:
    file: ${DIR_REQUIREMENTS}/mariadb/conf/50-server.cnf
  fpm_config:
    file: ${DIR_REQUIREMENTS}/wordpress/conf/www.conf
  adminer_config:
    file: ${DIR_REQUIREMENTS}/bonus/adminer/conf/www.conf
  adminer-index.php:
    file: ${DIR_REQUIREMENTS}/bonus/adminer/conf/index.php
  redis_config:
    file: ${DIR_REQUIREMENTS}/bonus/redis/conf/redis.conf
  ftp_config:
    file: ${DIR_REQUIREMENTS}/bonus/ftp/conf/vsftpd.virtual
  website_config:
    file: ${DIR_REQUIREMENTS}/bonus/website/conf/nginx.conf
  website_sites_available:
    file: ${DIR_REQUIREMENTS}/bonus/website/conf/default

secrets:
  server-certificate:
    file: ${DIR_SECRET}/site.crt
  server-key:
    file: ${DIR_SECRET}/site.key
  mariadb_root_password:
    file: ${DIR_SECRET}/mariadb_root_password.txt
  mariadb_wpuser_password:
    file: ${DIR_SECRET}/mariadb_wpuser_password.txt
  wordpress_admin_password:
    file: ${DIR_SECRET}/wordpress_admin_password.txt
  wordpress_user_password:
    file: ${DIR_SECRET}/wordpress_user_password.txt
  ftp_user_password:
    file: ${DIR_SECRET}/ftp_user_password.txt

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_DATA_WORDPRESS}
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_DATA_MARIADB}
      o: bind
