

services:

  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx/
      args:
        - CURRENT_UID=${CURRENT_UID}
        - CURRENT_GID=${CURRENT_GID}
    init: true
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
      - source: nginx_sites_available
        target: /etc/nginx/sites-available/default
    secrets:
      - source: server-certificate
        target: site.crt
      - source: server-key
        target: site.key
    depends_on:
      - wp-php
      - mariadb
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: /home/gwolf/data/wordpress
        target: /var/www/html
    networks:
      - inception

  wp-php:
    container_name: wp-php
    build:
      context: ./requirements/wordpress/
      args:
        - CURRENT_UID=${CURRENT_UID}
        - CURRENT_GID=${CURRENT_GID}
    init: true
    depends_on:
      - mariadb
    configs:
      - source: fpm_config
        target: /etc/php/8.2/fpm/pool.d/www.conf
    volumes:
      - type: bind
        source: /home/gwolf/data/wordpress
        target: /var/www/html
    networks:
      - inception
    secrets:
      - source: mariadb_wpuser_password
        target: mariadb_wpuser_password
    environment:
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - MARIADB_WPUSER_PASSWORD_FILE=${MARIADB_WPUSER_PASSWORD_FILE}
      - MARIADB_HOST=${MARIADB_HOST}
      - WP_CLI_CACHE_DIR=/var/www/html/

  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb/
      args:
        - CURRENT_UID=${CURRENT_UID}
        - CURRENT_GID=${CURRENT_GID}
        - MARIADB_VERSION=${MARIADB_VERSION}
    init: true
    configs:
      - source: mariadb_config
        target: /etc/mysql/mariadb.conf.d/50-server.cnf
    secrets:
      - source: mariadb_root_password
        target: mariadb_root_password 
      - source: mariadb_wpuser_password
        target: mariadb_wpuser_password
    volumes:
      - type: bind
        source: /home/gwolf/data/mariadb
        target: /var/lib/mysql
    networks:
      - inception
    environment:
      - MARIADB_VERSION=${MARIADB_VERSION}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_ROOT_PASSWORD_FILE=${MARIADB_ROOT_PASSWORD_FILE}
      - MARIADB_WPUSER_PASSWORD_FILE=${MARIADB_WPUSER_PASSWORD_FILE}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}

networks:
  inception:   
    name: inception

configs:
  nginx_config:
    file: ./requirements/nginx/conf/nginx.conf
  nginx_sites_available:
    file: ./requirements/nginx/conf/default
  mariadb_config:
    file: ./requirements/mariadb/conf/50-server.cnf
  fpm_config:
    file: ./requirements/wordpress/conf/www.conf

secrets:
  server-certificate:
    file: ../secrets/site.crt
  server-key:
    file: ../secrets/site.key
  mariadb_root_password:
    file: ../secrets/mariadb_root_password.txt
  mariadb_wpuser_password:
    file: ../secrets/mariadb_wpuser_password.txt

