services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    init: true
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
        mode: 0440
      - source: nginx_sites_available
        target: /etc/nginx/sites-available/default
        mode: 0440
    secrets:
      - source: server-certificate
        target: site.crt
        mode: 0440
      - source: server-key
        target: site.key
        mode: 0440
    depends_on:
      - wp-php
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  wp-php:
    container_name: wp-php
    build: ./requirements/wordpress/
    init: true
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
      - type: bind
        source: ./requirements/wordpress/conf/
        target: /etc/php/8.2/fpm/pool.d/
      - type: bind
        source: ./requirements/wordpress/tools/
        target: /tools/
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    init: true
    configs:
      - source: mariadb_config
        target: /etc/mysql/mariadb.conf.d/50-server.cnf
      - source: mariadb_init_db
        target: /etc/mysql/mariadb.conf.d/init.sql
    volumes:
      - mariadb:/var/lib/mysql
      - type: bind
        source: ./requirements/mariadb/tools
        target: /tools/
    networks:
      - inception

networks:
  inception:   
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver_opts:
      type: "nfs"
      o: 'bind'
      device: /home/gwolf/data/wordpress
  mariadb:
    name: mariadb
    driver_opts:
      type: "nfs"
      o: 'bind'
      device: /home/gwolf/data/mariadb

configs:
  nginx_config:
    file: ./requirements/nginx/conf/nginx.conf
  nginx_sites_available:
    file: ./requirements/nginx/conf/default
  mariadb_config:
    file: ./requirements/mariadb/conf/50-server.cnf
  mariadb_init_db:
    file: ./requirements/mariadb/conf/init.sql

secrets:
  server-certificate:
    file: ../secrets/site.crt
  server-key:
    file: ../secrets/site.key
