

services:

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      args:
        - CURRENT_UID=${CURRENT_UID}
        - CURRENT_GID=${CURRENT_GID}
    init: true
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
      - source: nginx_sites_available
        target: /etc/nginx/sites-available/default
    secrets:
      - source: server-certificate
        target: site.crt
      - source: server-key
        target: site.key
    depends_on:
      - wp-php
      - mariadb
    ports:
      - "443:443"
    volumes:
      - type: bind
        source: ${DIR_DATA_WORDPRESS}
        target: /var/www/html
    networks:
      - inception

  wp-php:
    container_name: wp-php
    build:
      context: ./requirements/wordpress/
      args:
        - CURRENT_UID=${CURRENT_UID}
        - CURRENT_GID=${CURRENT_GID}
    init: true
    depends_on:
      - mariadb
    configs:
      - source: fpm_config
        target: /etc/php/8.2/fpm/pool.d/www.conf
    volumes:
      - type: bind
        source: ${DIR_DATA_WORDPRESS}
        target: /var/www/html
    networks:
      - inception
    secrets:
      - source: mariadb_wpuser_password
        target: mariadb_wpuser_password
      - source: wordpress_admin_password
        target: wordpress_admin_password
      - source: wordpress_user_password
        target: wordpress_user_password
    environment:
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - WORDPRESS_ADMIN_MAIL=${WORDPRESS_ADMIN_MAIL}
      - WORDPRESS_ADMIN_PASSWORD_FILE=${WORDPRESS_ADMIN_PASSWORD_FILE}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_USER_MAIL=${WORDPRESS_USER_MAIL}
      - WORDPRESS_USER_PASSWORD_FILE=${WORDPRESS_USER_PASSWORD_FILE}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - MARIADB_WPUSER_PASSWORD_FILE=${MARIADB_WPUSER_PASSWORD_FILE}
      - MARIADB_HOST=${MARIADB_HOST}
      - WP_CLI_CACHE_DIR=${WP_CLI_CACHE_DIR}
      - DOMAIN_NAME=${DOMAIN_NAME}

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        - CURRENT_UID=${CURRENT_UID}
        - CURRENT_GID=${CURRENT_GID}
        - MARIADB_VERSION=${MARIADB_VERSION}
    init: true
    configs:
      - source: mariadb_config
        target: /etc/mysql/mariadb.conf.d/50-server.cnf
    secrets:
      - source: mariadb_root_password
        target: mariadb_root_password
      - source: mariadb_wpuser_password
        target: mariadb_wpuser_password
    volumes:
      - type: bind
        source: ${DIR_DATA_MARIADB}
        target: /var/lib/mysql
    networks:
      - inception
    environment:
      - MARIADB_VERSION=${MARIADB_VERSION}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_ROOT_PASSWORD_FILE=${MARIADB_ROOT_PASSWORD_FILE}
      - MARIADB_WPUSER_PASSWORD_FILE=${MARIADB_WPUSER_PASSWORD_FILE}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    depends_on:
      - mariadb
    init: true
    networks:
      - inception
    restart: always
    configs:
      - source: adminer_config
        target: /etc/php/8.2/fpm/pool.d/www.conf
      - source: adminer-index.php
        target: /var/www/html/index.php
    environment:
      - ADMINER_DEFAULT_DRIVER=server
      - ADMINER_DEFAULT_DB=${WORDPRESS_DB_NAME}
      - ADMINER_DEFAULT_SERVER=${MARIADB_HOST}
      - ADMINER_DEFAULT_USERNAME=${WORDPRESS_DB_USER}

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    depends_on:
      - wp-php
    restart: always
    configs:
      - source: redis_config
        target: /etc/redis/redis.conf
    volumes:
      - type: bind
        source: ${DIR_DATA_WORDPRESS}
        target: /var/www/html
    networks:
      - inception

  ftp:
    container_name: ftp
    build:
      context: ./requirements/bonus/ftp/
      args:
          - CURRENT_UID=${CURRENT_UID}
          - CURRENT_GID=${CURRENT_GID}
          - FTP_USER=${FTP_USER}
    depends_on:
      - wp-php
    init: true
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    networks:
      - inception
    restart: always
    volumes:
      - type: bind
        source: ${DIR_DATA_WORDPRESS}
        target: /home/${FTP_USER}/
    secrets:
      - source: ftp_user_password
        target: ftp_user_password
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_USER_PASSWORD_FILE=${FTP_USER_PASSWORD_FILE}

networks:
  inception:
    name: inception

configs:
  nginx_config:
    file: ./requirements/nginx/conf/nginx.conf
  nginx_sites_available:
    file: ./requirements/nginx/conf/default
  mariadb_config:
    file: ./requirements/mariadb/conf/50-server.cnf
  fpm_config:
    file: ./requirements/wordpress/conf/www.conf
  adminer_config:
    file: ./requirements/bonus/adminer/conf/www.conf
  adminer-index.php:
    file: ./requirements/bonus/adminer/conf/index.php
  redis_config:
    file: ./requirements/bonus/redis/conf/redis.conf
  ftp_config:
    file: ./requirements/bonus/ftp/conf/vsftpd.conf

secrets:
  server-certificate:
    file: ${DIR_SECRET}/site.crt
  server-key:
    file: ${DIR_SECRET}/site.key
  mariadb_root_password:
    file: ${DIR_SECRET}/mariadb_root_password.txt
  mariadb_wpuser_password:
    file: ${DIR_SECRET}/mariadb_wpuser_password.txt
  wordpress_admin_password:
    file: ${DIR_SECRET}/wordpress_admin_password.txt
  wordpress_user_password:
    file: ${DIR_SECRET}/wordpress_user_password.txt
  ftp_user_password:
    file: ${DIR_SECRET}/ftp_user_password.txt

