services:
  nginx:
    container_name: nginx
    build:
      context: ${DIR_REQUIREMENTS}/nginx/
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - NGINX_VERSION=${NGINX_VERSION}
        - CURL_VERSION=${CURL_VERSION}
    init: true
    restart: always
    depends_on:
      wp-php:
        condition: service_healthy
      mariadb:
        condition: service_healthy
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    secrets:
      - source: server-certificate
        target: site.crt
      - source: server-key
        target: site.key
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  wp-php:
    container_name: wp-php
    build:
      context: ${DIR_REQUIREMENTS}/wordpress/
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - PHP_FPM_VERSION=${PHP_FPM_VERSION}
        - PHP_MYSQL_VERSION=${PHP_MYSQL_VERSION}
        - CURL_VERSION=${CURL_VERSION}
        - WP_CLI_VERSION=${WP_CLI_VERSION}
    init: true
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    configs:
      - source: fpm_config
        target: /etc/php/7.4/fpm/pool.d/www.conf
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    secrets:
      - source: mariadb_wpuser_password
        target: mariadb_wpuser_password
      - source: wordpress_admin_password
        target: wordpress_admin_password
      - source: wordpress_user_password
        target: wordpress_user_password
    environment:
      - WORDPRESS_TITLE=${WORDPRESS_TITLE}
      - WORDPRESS_ADMIN=${WORDPRESS_ADMIN}
      - WORDPRESS_ADMIN_MAIL=${WORDPRESS_ADMIN_MAIL}
      - WORDPRESS_ADMIN_PASSWORD_FILE=${WORDPRESS_ADMIN_PASSWORD_FILE}
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_USER_MAIL=${WORDPRESS_USER_MAIL}
      - WORDPRESS_USER_PASSWORD_FILE=${WORDPRESS_USER_PASSWORD_FILE}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${USER_NAME}
      - MARIADB_WPUSER_PASSWORD_FILE=${MARIADB_WPUSER_PASSWORD_FILE}
      - MARIADB_HOST=${MARIADB_HOST}
      - WP_CLI_CACHE_DIR=${WP_CLI_CACHE_DIR}
      - DOMAIN_NAME=${DOMAIN_NAME}
    healthcheck:
      test: ["CMD", "wp", "core", "verify-checksums"]
      start_period: 5s
      interval: 10s
      timeout: 30s
      retries: 3
  mariadb:
    container_name: mariadb
    build:
      context: ${DIR_REQUIREMENTS}/mariadb/
      args:
        - USER_UID=${USER_UID}
        - USER_GID=${USER_GID}
        - MARIADB_VERSION=${MARIADB_VERSION}
    init: true
    restart: always
    configs:
      - source: mariadb_config
        target: /etc/mysql/mariadb.conf.d/50-server.cnf
    secrets:
      - source: mariadb_root_password
        target: mariadb_root_password
      - source: mariadb_wpuser_password
        target: mariadb_wpuser_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    environment:
      - MARIADB_VERSION=${MARIADB_VERSION}
      - MARIADB_HOST=${MARIADB_HOST}
      - MARIADB_ROOT_PASSWORD_FILE=${MARIADB_ROOT_PASSWORD_FILE}
      - MARIADB_WPUSER_PASSWORD_FILE=${MARIADB_WPUSER_PASSWORD_FILE}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${USER_NAME}
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 5s
      interval: 10s
      timeout: 30s
      retries: 3

networks:
  inception:
    name: inception

configs:
  nginx_config:
    file: ${DIR_REQUIREMENTS}/nginx/conf/nginx.conf
  mariadb_config:
    file: ${DIR_REQUIREMENTS}/mariadb/conf/50-server.cnf
  fpm_config:
    file: ${DIR_REQUIREMENTS}/wordpress/conf/www.conf

secrets:
  server-certificate:
    file: ${DIR_SECRET}/site.crt
  server-key:
    file: ${DIR_SECRET}/site.key
  ftp-certificate:
    file: ${DIR_SECRET}/ftp.crt
  ftp-key:
    file: ${DIR_SECRET}/ftp.key
  mariadb_root_password:
    file: ${DIR_SECRET}/mariadb_root_password.txt
  mariadb_wpuser_password:
    file: ${DIR_SECRET}/mariadb_wpuser_password.txt
  wordpress_admin_password:
    file: ${DIR_SECRET}/wordpress_admin_password.txt
  wordpress_user_password:
    file: ${DIR_SECRET}/wordpress_user_password.txt

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_DATA_WORDPRESS}
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${DIR_DATA_MARIADB}
      o: bind
